stages:
  load_data:
    cmd: python src/stages/load_data.py --config=params.yaml
    deps:
    - src/stages/load_data.py
  
  featurize:
    cmd: python src/stages/feature_engineering.py --config=params.yaml
    deps:
    - data/raw/ckd-dataset-v2.csv
    - src/stages/feature_engineering.py
    outs:
    - data/processed/preprocess_ckd_dataset_v2.csv

  data_split:
    cmd: python src/stages/data_split.py --config=params.yaml
    deps:
    - data/processed/preprocess_ckd_dataset_v2.csv
    - src/stages/data_split.py
    outs:
    - data/processed/train_ckd_dataset_v2.csv
    - data/processed/test_ckd_dataset_v2.csv

  train:
    cmd: |
      export PYTHONPATH=$(pwd) && python src/stages/train.py --config=params.yaml
    deps:
    - data/processed/train_ckd_dataset_v2.csv
    - src/model/model.py
    - src/stages/train.py
    outs:
    - models/model_${train.estimator_name}.pkl
    params:
    - train.estimator_name

  evaluate:
    cmd: |
      export PYTHONPATH=$(pwd) && python src/stages/evaluate.py --config=params.yaml
    deps:
    - data/processed/test_ckd_dataset_v2.csv
    - models/model_${train.estimator_name}.pkl
    - src/stages/evaluate.py
    outs:
    - reports/confusion_matrix_${train.estimator_name}.png
    - reports/metrics_${train.estimator_name}.json
    params:
    - train.estimator_name