base:
  random_seed: 42

data:
  # loading data
  filepath: './data/raw/ckd-dataset-v2.csv'
  header: 0
  skiprows: [1,2]

feature_engineering:
  target_column: 'class'
  categorical_columns: ['sg','al','su','bgr','bu','sod','sc','pot','hemo','pcv','rbcc','wbcc','grf','stage','age']
  features_path: './data/processed/preprocess_ckd_dataset_v2.csv'

data_split:
  test_size: 0.2
  train_path: './data/processed/train_ckd_dataset_v2.csv'
  test_path: './data/processed/test_ckd_dataset_v2.csv'

train:
  # training hyperparameters
  cv: 5
  estimator_name: log_reg
  estimators:
    log_reg: # sklearn.linear_model.LogisticRegression
      param_grid:
        C: [0.001]
        max_iter: [10]
        solver: ['lbfgs']
      model_path: './models/model_log_reg.pkl'

evaluate:
  # metrics, images, etc.
  reports_dir: './reports'
  target_names: ['not_ckd', 'ckd']
  estimators:
    log_reg:
      metrics_file: 'metrics_log_reg.json'
      confusion_matrix_img: 'confusion_matrix_log_reg.png'