name: Python Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run DVC Pipeline
        run: |
          dvc repro

      - name: Run tests with pytest
        run: |
          pytest src/tests/ --maxfail=1 --disable-warnings